### ISSUE TITLE
spiffe-helper as a native sidecar doesn't exit with code 0 when main container exits

### ISSUE THREAD

**Issue by keeganwitt** [spiffe/spiffe-helper#179]
When running a cronjob, with the helper as a [native sidecar](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/), the sidecar container exits with code 2 instead of 0. Here is an example of this, which uses host path agent sockets to communicate with SPIRE.

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: helper-conf
data:
  helper.conf: |
    agent_address = "/run/spire/agent/socket"
    jwt_svids = [
      {
        jwt_svid_file_name = "/etc/jwts/aws.jwt"
        jwt_audience = "sts.amazonaws.com"
      }
    ]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spiffe-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              image: busybox
              args: ['/bin/sh', '-c', 'date; sleep 5']
              volumeMounts:
                - name: jwts
                  mountPath: /etc/jwts
          initContainers:
            - name: wait-for-svid-registration
              image: ghcr.io/spiffe/spiffe-helper:nightly
              volumeMounts:
                - name: helper-conf
                  mountPath: /etc/spiffe-helper
                - name: spire-agent
                  mountPath: /run/spire/agent/socket
                - name: jwts
                  mountPath: /etc/jwts
              command: ["/spiffe-helper", "-config", "/etc/spiffe-helper/helper.conf", "-daemon-mode=false"]
            - name: spiffe-helper
              image: ghcr.io/spiffe/spiffe-helper:nightly
              restartPolicy: Always
              volumeMounts:
                - name: helper-conf
                  mountPath: /etc/spiffe-helper
                - name: spire-agent
                  mountPath: /run/spire/agent/socket
                - name: jwts
                  mountPath: /etc/jwts
              command: ["/spiffe-helper", "-config", "/etc/spiffe-helper/helper.conf"]
          restartPolicy: Never
          volumes:
            - name: helper-conf
              configMap:
                name: helper-conf
                items:
                  - key: helper.conf
                    path: helper.conf
            - name: spire-agent
              hostPath:
                type: Socket
                path: /run/spire/agent/socket
            - name: jwts
              emptyDir:
                medium: Memory
```

```
% kubectl get pod spiffe-job-28759386-vdjqk -o jsonpath='{.status}' | jq .
```

```json
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2024-09-05T19:06:11Z",
      "status": "False",
      "type": "PodReadyToStartContainers"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2024-09-05T19:06:04Z",
      "reason": "PodCompleted",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2024-09-05T19:06:10Z",
      "reason": "PodCompleted",
      "status": "False",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2024-09-05T19:06:10Z",
      "reason": "PodCompleted",
      "status": "False",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2024-09-05T19:06:00Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://c09b55a212011faf07d1233b3a81debe6e3b1c074089abf941f480e2886d994c",
      "image": "docker-registry.awscmhqa5.k8s.indeed.tech/dockerhub-proxy/library/busybox:latest",
      "imageID": "docker-registry.awscmhqa5.k8s.indeed.tech/dockerhub-proxy/library/busybox@sha256:ee39fe7af1f2bbfe72516d61b4d886a876c0ebfa263a6ebc5c132a744ed34ec3",
      "lastState": {},
      "name": "main",
      "ready": false,
      "restartCount": 0,
      "started": false,
      "state": {
        "terminated": {
          "containerID": "containerd://c09b55a212011faf07d1233b3a81debe6e3b1c074089abf941f480e2886d994c",
          "exitCode": 0,
          "finishedAt": "2024-09-05T19:06:09Z",
          "reason": "Completed",
          "startedAt": "2024-09-05T19:06:04Z"
        }
      }
    }
  ],
  "hostIP": "10.115.217.69",
  "hostIPs": [
    {
      "ip": "10.115.217.69"
    }
  ],
  "initContainerStatuses": [
    {
      "containerID": "containerd://8915adb4722aa78fff8c9507d3d5b36dd162cf9b161cc5df15b96fbe15a7ad32",
      "image": "ghcr.io/spiffe/spiffe-helper:nightly",
      "imageID": "ghcr.io/spiffe/spiffe-helper@sha256:6b09786251ae4e3ccef193b98eceae4b3d2bed091f3a8dd92be33a4c207455f2",
      "lastState": {},
      "name": "wait-for-svid-registration",
      "ready": true,
      "restartCount": 0,
      "started": false,
      "state": {
        "terminated": {
          "containerID": "containerd://8915adb4722aa78fff8c9507d3d5b36dd162cf9b161cc5df15b96fbe15a7ad32",
          "exitCode": 0,
          "finishedAt": "2024-09-05T19:06:02Z",
          "reason": "Completed",
          "startedAt": "2024-09-05T19:06:01Z"
        }
      }
    },
    {
      "containerID": "containerd://ea72e5c4c7e688adace7d46de48b43d090214f3d4b3972a5b2bd4a464d7d125f",
      "image": "ghcr.io/spiffe/spiffe-helper:nightly",
      "imageID": "ghcr.io/spiffe/spiffe-helper@sha256:6b09786251ae4e3ccef193b98eceae4b3d2bed091f3a8dd92be33a4c207455f2",
      "lastState": {},
      "name": "spiffe-helper",
      "ready": false,
      "restartCount": 0,
      "started": false,
      "state": {
        "terminated": {
          "containerID": "containerd://ea72e5c4c7e688adace7d46de48b43d090214f3d4b3972a5b2bd4a464d7d125f",
          "exitCode": 2,
          "finishedAt": "2024-09-05T19:06:10Z",
          "reason": "Error",
          "startedAt": "2024-09-05T19:06:03Z"
        }
      }
    }
  ],
  "phase": "Succeeded",
  "podIP": "10.75.66.4",
  "podIPs": [
    {
      "ip": "10.75.66.4"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2024-09-05T19:06:00Z"
}
```

This doesn't happen when spiffe-helper is run as a regular container (the old way of running sidecars) and instead the container keeps running since there's nothing to terminate the process when the main container exits currently.

**Comment by faisal-memon** [comment]
Thanks @keeganwitt for testing this out. Will be trying to reproduce this over the next few days.

**Comment by faisal-memon** [comment]
@keeganwitt looking at the config you have 2 spiffe helper init containers. Is this intended? The one with daemon mode disabled exits with code 0. The other one exits with code 2.

**Comment by keeganwitt** [comment]
Yes, this is intended. This happens even with just one sidecar. The intent here is that one sidecar (wait-for-svid-registration) blocks everything until the SVID is available (Registrar / Controller Manager creates the entry, it gets syncd to agent, etc). Then the other init container (spiffe-helper) runs as a sidecar to keep the SVID updated. This second container is what used to run as another non-init container before native sidecars were available.

**Comment by kfox1111** [comment]
Here's a simplified reproducer example that works with the helm chart:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: helper-conf
data:
  helper.conf: |
    agent_address = "/run/spire/agent/spire-agent.sock"
    jwt_svids = [
      {
        jwt_svid_file_name = "/etc/jwts/aws.jwt"
        jwt_audience = "sts.amazonaws.com"
      }
    ]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: spiffe-job
spec:
      template:
        spec:
          containers:
            - name: main
              image: busybox
              args: ['/bin/sh', '-c', 'date; sleep 5']
              volumeMounts:
                - name: jwts
                  mountPath: /etc/jwts
          initContainers:
            - name: wait-for-svid-registration
              image: ghcr.io/spiffe/spiffe-helper:nightly
              volumeMounts:
                - name: helper-conf
                  mountPath: /etc/spiffe-helper
                - name: spire-agent
                  mountPath: /run/spire/agent
                - name: jwts
                  mountPath: /etc/jwts
              command: ["/spiffe-helper", "-config", "/etc/spiffe-helper/helper.conf", "-daemon-mode=false"]
            - name: spiffe-helper
              image: ghcr.io/spiffe/spiffe-helper:nightly
              restartPolicy: Always
              volumeMounts:
                - name: helper-conf
                  mountPath: /etc/spiffe-helper
                - name: spire-agent
                  mountPath: /run/spire/agent
                - name: jwts
                  mountPath: /etc/jwts
              command: ["/spiffe-helper", "-config", "/etc/spiffe-helper/helper.conf"]
          restartPolicy: Never
          volumes:
            - name: helper-conf
              configMap:
                name: helper-conf
                items:
                  - key: helper.conf
                    path: helper.conf
```

Though I'm not getting the exit code 2 issue. Got exit code 0, but a stuck sidecar. not reaching the main phase.
